### ISSUE TITLE
When will audio data be made public？

### ISSUE THREAD

**Issue by lj1995513** [facebookresearch/TalkingWithHands32M#3]

**Comment by shugaoma** [comment]
As we target capturing spontaneous conversations and ask participants to chat without scripts, sometimes the participants may mention some personal information during their conversation.  Although these are typically non-sensitive information and we have consent for releasing the data from all participants, we are working on carefully inspecting and cleaning the audio to make sure any sensitive personal information is removed from the released audio. Due to the large volume of the audio data and the complexity nature of this manual inspection and cleaning, we can't make a commitment to a specific date at the moment but will release the audio so as soon as this task is done.

**Comment by Svito-zar** [comment]
I am also looking forward to see the audios.
Please let me know when you release it
